# Conexão com o Banco de Dados (MySQL Local - Sem Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/autopecas?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
# COLOQUE SUA SENHA DO MYSQL ABAIXO (ou deixe vazio se não tiver senha)
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (Migrações Automáticas)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Porta do Servidor
server.port=8081

# Exibir logs detalhados (opcional para debug)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
